export const services = [
  {
    id: 1,
    heroImage: "",
    sectionImage: "",
    name: "Accounting / Bookkeeping",
    link: "accounting-bookkeeping",
    subtitle:
      "Professional Accounting Services for Effective Financial Management",
    description:
      "Our accounting services are designed to help you manage your finances effectively. We provide comprehensive solutions, from bookkeeping to financial reporting, ensuring your business operates smoothly. Our team of experienced accountants is dedicated to maintaining the highest standards of accuracy and timeliness.",
    moreservices: [
      {
        id: 1,
        heroImage: "",
        sectionImage: "",
        name: "Service 1",
        link: "service-1",
        subtitle: "Service 1 subtitle",
        description: "Service 1 description",
      },
      {
        id: 2,
        heroImage: "",
        sectionImage: "",
        name: "Service 2",
        link: "service-2",
        subtitle: "Service 2 subtitle",
        description: "Service 2 description",
      },
      {
        id: 3,
        heroImage: "",
        sectionImage: "",
        name: "Service 3",
        link: "service-3",
        subtitle: "Service 3 subtitle",
        description: "Service 3 description",
      },
      {
        id: 4,
        heroImage: "",
        sectionImage: "",
        name: "Service 4",
        link: "service-4",
        subtitle: "Service 4 subtitle",
        description: "Service 4 description",
      },
      {
        id: 5,
        heroImage: "",
        sectionImage: "",
        name: "Service 5",
        link: "service-5",
        subtitle: "Service 5 subtitle",
        description: "Service 5 description",
      },
      {
        id: 6,
        heroImage: "",
        sectionImage: "",
        name: "Service 6",
        link: "service-6",
        subtitle: "Service 6 subtitle",
        description: "Service 6 description",
      },
    ],
  },
  {
    id: 2,
    heroImage: "",
    sectionImage: "",
    name: "Payroll",
    link: "payroll",
    subtitle: "Reliable Payroll Services for Accurate Employee Management",
    description:
      "Streamline your payroll process with our dependable payroll services. We specialize in managing every aspect of payroll, ensuring your employees are paid accurately and on time. Our services include calculating paychecks, managing tax withholdings, processing direct deposits, and preparing year-end tax forms. Let us handle the complexities of payroll, allowing you to focus on growing your business.",
    moreservices: [
      {
        id: 1,
        heroImage: "",
        sectionImage: "",
        name: "Service 1",
        link: "service-1",
        subtitle: "Service 1 subtitle",
        description: "Service 1 description",
      },
      {
        id: 2,
        heroImage: "",
        sectionImage: "",
        name: "Service 2",
        link: "service-2",
        subtitle: "Service 2 subtitle",
        description: "Service 2 description",
      },
      {
        id: 3,
        heroImage: "",
        sectionImage: "",
        name: "Service 3",
        link: "service-3",
        subtitle: "Service 3 subtitle",
        description: "Service 3 description",
      },
      {
        id: 4,
        heroImage: "",
        sectionImage: "",
        name: "Service 4",
        link: "service-4",
        subtitle: "Service 4 subtitle",
        description: "Service 4 description",
      },
      {
        id: 5,
        heroImage: "",
        sectionImage: "",
        name: "Service 5",
        link: "service-5",
        subtitle: "Service 5 subtitle",
        description: "Service 5 description",
      },
      {
        id: 6,
        heroImage: "",
        sectionImage: "",
        name: "Service 6",
        link: "service-6",
        subtitle: "Service 6 subtitle",
        description: "Service 6 description",
      },
    ],
  },
  {
    id: 3,
    heroImage: "",
    sectionImage: "",
    name: "Tax",
    link: "taxing",
    subtitle: "Expert Tax Services for Efficient Tax Management",
    description:
      "Navigating the complexities of taxes can be challenging. Our expert tax services are here to help. We offer tax planning, preparation, and filing services to keep your business compliant. Our tax professionals stay updated on the latest tax laws to ensure you take advantage of all applicable tax benefits.",
    moreservices: [
      {
        id: 1,
        heroImage: "",
        sectionImage: "",
        name: "Service 1",
        link: "service-1",
        subtitle: "Service 1 subtitle",
        description: "Service 1 description",
      },
      {
        id: 2,
        heroImage: "",
        sectionImage: "",
        name: "Service 2",
        link: "service-2",
        subtitle: "Service 2 subtitle",
        description: "Service 2 description",
      },
      {
        id: 3,
        heroImage: "",
        sectionImage: "",
        name: "Service 3",
        link: "service-3",
        subtitle: "Service 3 subtitle",
        description: "Service 3 description",
      },
      {
        id: 4,
        heroImage: "",
        sectionImage: "",
        name: "Service 4",
        link: "service-4",
        subtitle: "Service 4 subtitle",
        description: "Service 4 description",
      },
      {
        id: 5,
        heroImage: "",
        sectionImage: "",
        name: "Service 5",
        link: "service-5",
        subtitle: "Service 5 subtitle",
        description: "Service 5 description",
      },
      {
        id: 6,
        heroImage: "",
        sectionImage: "",
        name: "Service 6",
        link: "service-6",
        subtitle: "Service 6 subtitle",
        description: "Service 6 description",
      },
    ],
  },
  {
    id: 4,
    heroImage: "",
    sectionImage: "",
    name: "Finance",
    link: "financing",
    subtitle: "Comprehensive Financial Services for Business Growth",
    description:
      "Our financial services go beyond basic accounting and bookkeeping. We offer financial planning, budgeting, and forecasting services to help your business grow. Our financial experts work closely with you to understand your business goals and develop a financial strategy that aligns with them.",
    moreservices: [
      {
        id: 1,
        heroImage: "",
        sectionImage: "",
        name: "Service 1",
        link: "service-1",
        subtitle: "Service 1 subtitle",
        description: "Service 1 description",
      },
      {
        id: 2,
        heroImage: "",
        sectionImage: "",
        name: "Service 2",
        link: "service-2",
        subtitle: "Service 2 subtitle",
        description: "Service 2 description",
      },
      {
        id: 3,
        heroImage: "",
        sectionImage: "",
        name: "Service 3",
        link: "service-3",
        subtitle: "Service 3 subtitle",
        description: "Service 3 description",
      },
      {
        id: 4,
        heroImage: "",
        sectionImage: "",
        name: "Service 4",
        link: "service-4",
        subtitle: "Service 4 subtitle",
        description: "Service 4 description",
      },
      {
        id: 5,
        heroImage: "",
        sectionImage: "",
        name: "Service 5",
        link: "service-5",
        subtitle: "Service 5 subtitle",
        description: "Service 5 description",
      },
      {
        id: 6,
        heroImage: "",
        sectionImage: "",
        name: "Service 6",
        link: "service-6",
        subtitle: "Service 6 subtitle",
        description: "Service 6 description",
      },
    ],
  },
  {
    id: 5,
    heroImage: "",
    sectionImage: "",
    name: "Team as a Service",
    link: "team-as-a-service",
    subtitle: "Dedicated Team Services for Exclusive Financial Operations",
    description:
      "Need a dedicated team to handle your financial operations? Our 'Team as a Service' provides you with a group of skilled professionals who work exclusively for your business. This service allows you to have a full-fledged finance team without the overhead costs of hiring and training.",
    moreservices: [
      {
        id: 1,
        heroImage: "",
        sectionImage: "",
        name: "Service 1",
        link: "service-1",
        subtitle: "Service 1 subtitle",
        description: "Service 1 description",
      },
      {
        id: 2,
        heroImage: "",
        sectionImage: "",
        name: "Service 2",
        link: "service-2",
        subtitle: "Service 2 subtitle",
        description: "Service 2 description",
      },
      {
        id: 3,
        heroImage: "",
        sectionImage: "",
        name: "Service 3",
        link: "service-3",
        subtitle: "Service 3 subtitle",
        description: "Service 3 description",
      },
      {
        id: 4,
        heroImage: "",
        sectionImage: "",
        name: "Service 4",
        link: "service-4",
        subtitle: "Service 4 subtitle",
        description: "Service 4 description",
      },
      {
        id: 5,
        heroImage: "",
        sectionImage: "",
        name: "Service 5",
        link: "service-5",
        subtitle: "Service 5 subtitle",
        description: "Service 5 description",
      },
      {
        id: 6,
        heroImage: "",
        sectionImage: "",
        name: "Service 6",
        link: "service-6",
        subtitle: "Service 6 subtitle",
        description: "Service 6 description",
      },
    ],
  },
  {
    id: 6,
    heroImage: "",
    sectionImage: "",
    name: "Consultation & Advisory",
    link: "consultation-advisory",
    subtitle: "Strategic Consultation Services for Informed Business Decisions",
    description:
      "Our consultation and advisory services are designed to provide strategic insights into your business. We help you make informed decisions to drive growth and profitability. Our consultants analyze your business operations, identify opportunities for improvement, and provide actionable recommendations.",
    moreservices: [
      {
        id: 1,
        heroImage: "",
        sectionImage: "",
        name: "Service 1",
        link: "service-1",
        subtitle: "Service 1 subtitle",
        description: "Service 1 description",
      },
      {
        id: 2,
        heroImage: "",
        sectionImage: "",
        name: "Service 2",
        link: "service-2",
        subtitle: "Service 2 subtitle",
        description: "Service 2 description",
      },
      {
        id: 3,
        heroImage: "",
        sectionImage: "",
        name: "Service 3",
        link: "service-3",
        subtitle: "Service 3 subtitle",
        description: "Service 3 description",
      },
      {
        id: 4,
        heroImage: "",
        sectionImage: "",
        name: "Service 4",
        link: "service-4",
        subtitle: "Service 4 subtitle",
        description: "Service 4 description",
      },
      {
        id: 5,
        heroImage: "",
        sectionImage: "",
        name: "Service 5",
        link: "service-5",
        subtitle: "Service 5 subtitle",
        description: "Service 5 description",
      },
      {
        id: 6,
        heroImage: "",
        sectionImage: "",
        name: "Service 6",
        link: "service-6",
        subtitle: "Service 6 subtitle",
        description: "Service 6 description",
      },
    ],
  },
];
